osmandapp/OsmAnd-resources

obf_creation/rendering_types.xml

Roads with "abutters" set may indicate whether the road is in a city (place) or not. Basing e.g. maxspeed on this tag can be beneficial for some countries.
And the "toll" rule seemed to be duplicate so I remove it.

Add "abutters" tag to routing section.

---

routing/routing.xml

Add this moment there are no penalties when going from motorway to motorway_link (and trunk to trunk_link). It sometimes happens that when a motorway_link exiting from a motorway, running parallel to the motorway, and leading back to the motorway is chosen by OsmAnd. This happens when the motorway_link is the inner bend and the motorway is the outer bend, causing the motorway_link to be 1-2 seconds faster (in theory).
The other requirement is that both the motorway and motorway_link don't have a maxspeed or have the same maxspeed.
Additionally I lowered the overall select value as in cities the value of 250 is a bit too much. For longer routes it is less critical.
Solution for penalties contributed by Peter B. in the mailing list.
Lowering overall value based on an issue in the mailing …

Update routing.xml; Refine penalties

---

routing/routing.xml

It seems the the default is access=no, unless marked otherwise (which OsmAnd already checks).
The other changes are just cleanup and lowering the time needed to cross an entrance/gate/restrictor with a car when it is passable for a car (passes the access checks).
(Once OsmAnd supports getting the height of the vehicle, barrier=height_restrictor can be checked against the height and the passed without much penalty).

make barrier=gate impassable to a car by default

---

obf_creation/rendering_types.xml

http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dapartment . Is it also necessary to assign an icon to it in some other file?

Add tourism=apartment to rendering_types.xml

---

routing/routing.xml

Some values of "abutters" mean that the road is inside a place (village, city, town), so a speed limit can apply. See http://wiki.openstreetmap.org/wiki/Abutters and https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Maxspeed . It is not easily possible to determine this information from landuse or other methods (see the comments there), for some countries. For countries where it is possible is OsmAnd preprocessing the map files to include this information in some way?

Observe "abutters" tag in routing.xml.

---

routing/routing.xml

Allow avoiding border crossings in car/bicycle routing. This can be useful for concave country parts (where the best route would be a shortcut trough another country). Or when there is a motorway near the border in the neighbouring country and OsmAnd would pick that as the fastest road. I have a real example of this case on a 400km trip (that OsmAnd calculated). It may be preferrable to avoid the foreign country, e.g. due to visa requirements, tolls, insurance coverage, etc. Of course best would be if OsmAnd considered administrative boundary relations to determine if a road is crossing into another country, but that is probably quite expensive for computation.

Allow avoiding border crossings in car/bicycle routing.

---

poi/phrases/it/phrases.xml

There was a misspelling town_hall istead of townhall.

Fix for "Can't find poi typre for poi reference 'town_hall'

---

routing/routing.xml

I propose to add more weight options in routing.xml. Until there is a proper support for buses and hgvs in a special routing profile, I think these options need to be in car profile.
I wonder when HGV profile gets supported, it already can be enabled via developer plugin in OsmAnd. But there seem no special settings for it in routing.xml. I'd be happy if OsmAnd got a HGV and BUS profiles. Some of the maxheight, maxweight, maxlength and access options could be moved there so that the car profile does not have too many unnecessary options.

Add more weight options in routing.xml

---

routing/routing.xml

So let's support maxheight in car routing. Do not allow a road that cannot accomodate a car with the user chosen height.
I hope the fractional values will work for numeric parameters. I use type=length as discussed in pull request #1188.

Add support for maxheight in routing.xml

---

obf_creation/rendering_types.xml

I think the "access" rule seems to be duplicate. The "toll_booth" key rule seems strange as there are no serious usages of such key in OSM data.
I add tourist_bus access key as that can be used similarly to "bus" in routing.

Remove duplicate routing rule in rendering_types.xml

---

routing/routing.xml

The tags of oneway=reverse (not reversible) and oneway=+1 aren't used in the world, see http://taginfo.openstreetmap.org/keys/oneway . So we can probably get some speed by not looking for them.

Remove unused oneway tags in routing.xml

---

obf_creation/rendering_types.xml

This tag is useful in for routing in some countries and in customized routing.xml files. See e.g. https://groups.google.com/forum/#!topic/osmand/W9cGkY9sOwU

add motorroad into routing section of rendering_types.xml

---

routing/routing.xml

Access=official (and variants of it like bicycle=official and foot=official) are used quite a lot and and the roads should be at least as allowed and preferred as =designated. Let's support the value so that we mistakenly do not avoid roads like bicycle=official+vehicle=no.

Support access=official in routing.xml

---

routing/routing.xml

Improve priority of roads when bicycle=official/private/destination is set. Reorder the rules so that it makes sense for the first hit to win. E.g. cycleway=* should win even when bicycle=yes is set.

Support some more access rules in bicycle mode

---

obf_creation/rendering_types.xml
routing/routing.xml

pedestrian=* is an undocumented tag, is used only 600 times in the world and is seems people use it instead of foot=*. So convert it to foot=* so that we do not need to check for it in routing.xml.

Convert pedestrian=* to foot=* in rendering_types.xml

---

voice/ja/ttsconfig.p

Current Japanese TTS resource is not comfortable because send texts to TTS engine is romanization Japanese.
Checked with 「Googleテキスト読み上げエンジン」or「KDDILABS N2 TTS」 (de-facto standard Japanese TTS engine), some glitches are included in speech with current implementation.
The texts sending to TTS should be Japanese native characters. This way fixes glitches in navigation.
And, route_new_calc/route_recalc does not work currently. This pull-request also fixes it.

voice/ja: Send native characters to TTS engine.

---

routing/routing.xml

See http://wiki.openstreetmap.org/wiki/Tag:bicycle%3Duse_sidepath for how the tag is to be used.
At http://wiki.openstreetmap.org/wiki/Proposed_features/use_sidepath#Routing they specifically call out OsmAnd as not supporting the tag yet.
We could use value="-1" for some countries, while for some countries using such ways for foot/bicycle may still be allowed. So reducing the priority may be the middle ground.

Discourage ways with *=use_sidepath (copy of issue #338)

---

routing/routing.xml

Support various types of pedestrian crossings in routing.xml. I think not all crossing types should have the same obstacle time.
In car mode, if the pedestrian crossing=uncontrolled, then there will probably not be such a long wait time (15 secs) as for crossing=traffic_signals, or highway=crossing (type undefined). But for crossing=unmarked, the car probably has priority, so make the obstacle time really small.
In foot mode, crossing unmarked and uncontrolled may incur some wait time, as cars may pass. On crossing=traffic_signals, the wait time can be longer. crossing=no means it is not passable so I add value=-1 to obstacle. The wiki allows adding these to the way (not only the junction node), so I put that also in "access" block.
Similarly for bike mode. …

Support various types of pedestrian crossings in routing.xml

---

voice/en/ttsconfig.p

Fix case when hours > 0 and minutes = 0 (eg. 2 hours, 0 minutes)
Behaviour before change: '2 hours minutes' for prerecorded and '2 hours 00 minutes' for TTS
Behaviour after change: '2 hours' for both options.'

Fix time(Sec) when hours>0 and minutes=0

---

voice/cs/ttsconfig.p

- Corrected declension of kilometry/kilometrů (kilometers)
- Corrected declension of hodiny/hodin (hours)
- Corrected declension of minuty/minut (minutes)
- Corrected declension of dva/dvě (two)
- Added missing spaces
- Added support for Attention: type [speed_camera, border_control, railroad_crossing, traffic_calming, toll_booth, stop, pedestrian_crosswalk]
- Corrected word order in time.ogg and keep_left/bear_left
- Translated missing strings
- Announcement of favorites, waypoints and pois along the route
- Announcement when user returns back to route
- Added proper declension of distance
Everything should be working fine -- tested by myself on drive and also by developer plugin.
Big thanks to @sonoma for telling difference between bear and keep.

Update Czech TTS

---

poi/phrases/it/phrases.xml

This is because adding a "Farmacia" POI in OsmAnd should insert amenity=pharmacy, not shop=chemist.
In Italy there are not "Chemist" shops, the more similar kind of shop is the "mesticheria", which sells various goods for housekeeping and personal care.

Changed translation for poi_chemist, which is not "Farmacia" in Italian.

---

routing/routing.xml

I think whith this little modification [#1202](https://github.com/osmandapp/Osmand/issues/1202) is fixed.
The motorway_link ending/coming from a motorway, so I think, it is not necessary to add this to the routing.xml

Deleted motorway_link from car navigation

---

icons/svg/emergency/fire_hydrant_underground.svg
icons/svg/emergency/suction_point.svg
icons/tools/sortfiles.sh

I would like to add icon for tag emergency=suction_point and emergency=fire_hydrant with fire_hydrant:type=underground. It is described on wiki page:
http://wiki.openstreetmap.org/wiki/Tag:emergency%3Dsuction_point
http://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant
I added only icon without any changes to default style. That icon should be optional and used only with custom rendering styles. It is very useful for e.g. for firefighters.
That icon could be accessed by custom style like:
```
<renderingStyle name="fire_hydrant.render" depends="default" defaultColor="#f1eae4" version="1">
<point>
<filter minzoom="10" icon="emergency_suction_point" tag="emergency" value="suction_point"/>
</point>
</renderingStyle>
```

Icons for underground fire hydrant and suction point.

---

rendering_styles/default.render.xml

Default OsmAnd style contains different but very close colors for residential and industrial areas. I think industrial should be a bit darker (and of course still no prominent).
https://www.dropbox.com/s/pk7hz3cqstvz2q0/Ind.png?dl=0
https://www.dropbox.com/s/u1h4d8j4nu4rzr9/Ind_new.png?dl=0

Make landuse=industrial darken than residential

---

obf_creation/rendering_types.xml

I dotn't want to discuss, should osmand strictly obey rules or not,  but set bicycle=destination on highway=living_street is really not a good idea. Alternative route will probably go via alongside footways, highway=service+living_street=yes or via main roads.
Here is an example http://bit.ly/29zjXqk (inconvenient route with 2 left turns, but osmand did something weird https://www.dropbox.com/s/cqtjcmltvkbnxei/weird_route.png?dl=0).

Allow cyclists to use living_streets

---

obf_creation/rendering_types.xml

Paths with bicycle=official should be rendered the same way as ones with bicycle=designated.

Add bicycle=official

---

routing/routing.xml

Sometimes highway lines didn't have access tags but access restricted with point barriers. Unfortunately, I found that access private and destination missed in point obstacles. Considering that ways with access=private and destination strongly deprioritized, but not avoided, I've introduced large penalties for this points. I'm not sure about exact values, at least, the longer is the alternative route, the greater they must be, but 60 and 180 seemed to be OK for motorcar (but not for foot, because 3 additional minutes for foot route doesn't change the situation).
Some examples for tests:
1) road between 2 lift gates with access=destination http://map.project-osrm.org/?z=14&center=55.457835%2C36.858187&loc=55.471386%2C36.869988&loc=55.444693%2C36.822696&hl=en&alt=0 (OsmAnd did motorcar …

Consider points with access=private and destination

---

voice/sk/ttsconfig.p

Commit 205bb4b added commas when concatenating distance.ogg so it does not need to contain the comma a second time.

Remove needless comma in sk/ttsconfig.p

---

voice/uk/ttsconfig.p

In one part of file used "metrOv" (tr. from RU) in other part "metrIv" (tr. from UA)

Fix translation issue. UA

---

rendering_styles/default.render.xml

Pink is one of the least used colours on the map, making it a good choice for clearly showing GPX tracks. Pink was previously available in OsmAnd 2.5 but removed in 2.6.

Add support for showing GPX tracks in pink

---

voice/en-gb/ttsconfig.p

In the UK everyone says 'speed camera", never abbreviating it to "speed cam".
Similarly the term always used is "toll barrier", never "toll booth".
The spelling of "favorite" is changed to "favourite" is changed to improve the pronunciation.
I have tested these changes by copying in the changed _ttsconfig.p file and using the OsmAnd Developer plugin.

en-gb TTS voice: some minor wording changes

---

rendering_styles/default.render.xml

**Show place_of_worship at z14+ if moreDetailed="true"**
This is a proposal based on the comparison of Osmand with classic 1:50000 – 1:25000 touristic and topographic paper maps that usually show *place_of_worship* features as POIs (e.g., generally associated to art/cultural monuments, also being orienteering references for hikers and for worship scope).
At the moment Osmand renders them at z16+. This PR will show *place_of_worship* at z14+ if *moreDetailed* is set.

Show place_of_worship at z14+ if moreDetailed="true"

---

rendering_styles/default.render.xml

**Improve visibility of mountain huts if moreDetailed="true"**
Mountain huts are reference buildings within undeveloped zones (typically in the mountains) and should be rendered at wide zooms.
With this PR, *alpine_hut* and *wilderness_hut* will be most probably rendered at z14+ or z15+ (before, some *alpine_hut* like [Rifugio Rino Olmo]( https://www.openstreetmap.org/way/120656176) was rendered at z18+).
This proposal is based on the comparison of Osmand with classic 1:50000 – 1:25000 touristic and topographic paper maps, that usually show these features.
I tried to reuse a similar design pattern to [Tweak place_of_worship order](https://github.com/osmandapp/OsmAnd-resources/commit/10184e1501f759724d184f1ab01f5b35fe7f52e4#diff-aa68e561bc04596c485828a0f39f460c).

Improve visibility of mountain huts if moreDetailed="true"

---

obf_creation/rendering_types.xml
rendering_styles/default.render.xml

**Revised text attributes and size of *natural=valley***
Removed rendering of polylines for valleys tagged as ways.
Valleys are rendered at z11+.
(With a separate PR, big valleys should be visible from z8+ anyway.)
Samples:
zoom=10: none shown as this is the basemap
zoom=11 (first zoom level of the detailed map)
zoom=12
zoom=13
zoom=14
zoom=15
zoom=16

Revised text attributes and size of natural=valley

---

obf_creation/rendering_types.xml
rendering_styles/default.render.xml
rendering_styles/topo.render.xml

**Improve text size and related order for *region:type=mountain_area***
Edit: this part is superseded by the subsequent note (see. "Code revised.").
_________________
After this modification, *region:type=mountain_area* will be rendered starting at z11+ (before it was rendered only at z13+).
This PR should be complemented in order to also allow showing this feature at z8, z9 and z10. I do not know of how to do it, even if *rendering_types.xml* is correctly set. Notice that even now that *rendering_types.xml* sets z10+, *region:type=mountain_area* is not rendered at that zoom.
Samples after this code is merged, all related to [this wide feature](http://www.openstreetmap.org/relation/2506537):
Text shown at z11
Text not shown at z10, even if it should be
Text not shown at z9, even if it …

Improve text size and related order for region:type=mountain_area

---

rendering_styles/default.render.xml

**Show text label for *natural=rock* in case of ways/polygons (and not only for nodes).**
As *natural=rock* is converted to *natural=bare_rock* for "way" in *rendering_types.xml*, the text label for *natural=bare_rock* is added.
Notice that this change does not yet add "natural_stone" icon to "bare_rock", just assuming that this is really wanted (otherwise,  `<case minzoom="17" tag="natural" value="bare_rock"/>` shall also be added before `<apply icon="natural_stone" shield="stone_shield"/>`).

Show text label for natural=rock

---

rendering_styles/default.render.xml

Revised rendering of *natural=valley* using a similar pattern to [*natural=ridge* and *natural=arete*](https://github.com/osmandapp/OsmAnd-resources/pull/470).

Revised rendering of natural=valley

---

routing/routing.xml

We should probably not route over highway=proposed roads even if they have explicit access tags. There is no road yet (even not partly constructed) so no means of transport can pass yet.
See https://groups.google.com/d/msg/osmand/0O0hvbVaXCg/4v3YKl-DBwAJ with a real world example https://www.openstreetmap.org/way/263684442 .
We don't want to eliminate higway=proposed objects before creating the obf file as we do render planned objects in OsmAnd (based on user setting).

Avoid routing over proposed roads

---

rendering_styles/default.render.xml

**Revised text attributes and size of *natural=ridge* and *natural=arete***
Now polylines are rendered only from zoom 6 to zoom 10; in order to show them at these zooms, the maps provided with Osmand shall be complemented with a specific layer (as the one attached [here](https://github.com/osmandapp/OsmAnd-resources/pull/458#issuecomment-345872380)).
Removed rendering of polylines from zoom 11 on (as done with [valleys](https://github.com/osmandapp/OsmAnd-resources/pull/459)).

Revised text attributes and size of natural=ridge and natural=arete

---

voice/cs/ttsconfig.p

- prepositions read as initials after turn
“odbočte na K Vozovně“ was read as “odbočte na K. Vozovně”
- time estimate read in genitive instead of nominative
“potřebná doba 45 minut“ was read as “potřebná doba čtyřiceti pěti minut”

Fixed issues with Czech Google TTS by using colons

---

voice/pl/config.p
voice/pl/ttsconfig.p

e.g. “ograniczenie prędkości 50” was read as “ograniczenie prędkości pięćdziesięciu”.
There is still some bad grammer left, especially when reading `ref` or `destiantion:ref` values in specific contexts. Additionally, street names are not read in the accusative form in turn commands.

Fix some grammar in pl voice

---

voice/cs/ttsconfig.p

- use “doprava/doleva” instead of “vpravo/vlevo“ for direction
- recalculation is announced when it is done, not when it starts
- traffic calming may be more than just bump or hump, use more generic term; see also issue osmandapp/OsmAnd#5605

Updated Czech TTS

---

routing/routing.xml

As vshcherb mentioned, it _does_ matter if you use `$` or `:` to call variables. This was noted incorrectly - which is now removed.

Fixed small error in documentation

---

voice/ja/ja_tts.js
voice/ja/ttsconfig.p

After using OsmAnd with the TTS voice in Japanese, I've noticed a few mistakes that I have now corrected in the ttsconfig.p file.
First of all, the prepositions "at", "in", "onto", "toward", etc. in Japanese go at the end of the word they're referring to. Previously the TTS placed them at the beginning of each word, which is ungrammatical.
Then, the 17 lines for each ordinal numbers (1st to 17th) had the ordinal (the 'st' in first, for example) detached from each number. This caused a situation in which English lines were used for the Japanese TTS, which in turn produced situations like "1st." being read as "いちストーンドット"　(1 stone dot). Using the previous detached ordinal, I was not able to get consistent behaviour from my device's TTS. This has been corrected by attaching 番目 (the 'th') to …

Updated Japanese TTS

---

voice/nl/nl_tts.js

At first when there was a pedestrian crosswalk OsmAnd would notify to watch out for a zebra.
As a pedestrian crosswalk is called "zebra pad" in Dutch I changed it to "zebra pad".
As I do not know how to change the pedestrian_crosswalk.ogg sound, this is still open to be changed.

Changed pedestrian crosswalk text on Dutch TTS

---

routing/routing.xml

Hello,
I'm from Bruges. We have a lot of cobblestones, which are not that easy to cycle on. Therefore, I mapped all the surface areas there, and edited the routing profile to have a router.
I hope that adding an extra option in the routing profile will be useful for a lot of people - at least in Bruges and other similar cities it will be useful for others. An due to streetcomplete, the data is becoming complete in other regions as well - so I hope it will be useful around the world. 
Clarification-edit: this PR adds an extra checkbox "avoid sett & cobblestone" in the 'avoid'-section of navigation options. It is disabled by default.

Add cobblestone avoidance

---

voice/sk/sk_tts.js

It seems this typos slipped in at the conversion from prolog. The string is named "hours3_4".
Other than this, the conversion seems OK, and the file is working beautifully in OsmAnd 3.3. Thanks for doing the manual conversion for all languages!

Fix 3-4 hours in sk_tts.js

---

voice/ar/ar_tts.js

Special grammar: agreement of number and singular/dual/plural form of unit  
Special grammar: agreement of number and unit gender  
Special grammar: nominative vs. genitive/accusative distinction  
Special grammar: word order with ordinal numbers  
Added a lot of strings for numbers to allow for case gender distinction and a function to convert from int's to those strings. Rephrased some instructions to be less verbose. I may have been a little too pedantic with the harakaat in a few places in an attempt to force correct pronunciation (e.g. مئتَيْنِ instead of مئتِينَ).  
Should only affect TTS, a lot of new .ogg's would be needed to achieve the same effect.  
Tested with A Capela and Vocalizer.

Improve Arabic TTS

---

voice/es/es_tts.js

To make the instructions shorter when approaching a roundabout I propose to change "in 450 meters enter the roundabout and take the first exit" to "in 450 meters at the roundabout take the first exit". 
In other languages ​​I don't know if it's shorter or not, but at least in Spanish it's shorter and clearer and in English it's slightly shorter

Improvements in roundabouts

---

obf_creation/rendering_types.xml

When testing the ski routing, I noticed that ski routing would sometimes follow the outline of a ski piste - sometimes even going up onto the mountain...
This pull request adds a tag transform to add an "access=no" tag onto areas, resulting in this correct route planning:
Please merge at least one month before the skiing season begins ;p

Fix bug: ski routing does not take edges of decorative piste outline anymore

---

rendering_styles/LightRS.render.xml

Default order for waterway is 9, and it more than bridge order and other

Fix for waterway order in LightRS style

---

rendering_styles/LightRS.render.xml

I made a mistake in the previous pull-request. And now I correct it. Revert order for waterway and add order="10" for bridge area without cycle="true"

Fix for waterway and bridge orders in LightRS style

---

obf_creation/rendering_types.xml

This adds support for the newly approved camp_pitch tag, which is for individual camps within a camp_site. Currently camp_pitch is not included in the OBF file, so disappears from the map.

Add support for camp_pitch

---

obf_creation/rendering_types.xml

`sidewalk=separate` is used if a highway does have a sidewalk, but it is mapped as a separate way. Osmand should treat this way as if it doesn't have a sidewalk. Only this way correct routing is possible (at least if the penalty for `sidewalk=no` is high enough).

sidewalk=separate => sidewalk=no

---

obf_creation/rendering_types.xml

iD editor invented its own needless duplicate tag and is polluting the OSM database with it. Let's convert it to the proper value to recognize this type of crossing.

Convert crossing=marked to uncontrolled

---

routing/routing.xml

In Line 500 is properly mentioned maxwidth. Thus in line 503 width has to be mentioned.

routing should consider as well the width tag.

---

voice/es/es_tts.js

As I said in https://github.com/osmandapp/OsmAnd-resources/pull/604  I think In spanish "and take the exit..." is better than "to exit..." because it is more clear and it is not much more longer (only 2 characteres more).

Update Exit Num (Spanish)

---

routing/routing.xml

12 tons seems to be an important max. value in the truck industry.
30 tons was added to simply have a smaller gap between 20t and 40t
see mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/osmand/66wqaInupU4/2QVS5rY0AgAJ

add 12t and 30t to permitted weight

---

poi/phrases/be/phrases.xml

Added:
<string name="poi_pump_status_out_of_order">Стан помпы: не функцыянуе</string>
<string name="poi_pump_status_missing_beam">Стан помпы: адсутнічае рычаг</string>

Added poi_pump_status_out_of_order and poi_pump_status_missing_beam

---

routing/routing.xml

I think changing these parameters will achieve better routing times in public transport.
Changing bus speed to "$maxspeed" https://github.com/osmandapp/Osmand/issues/6827 will be fixed. With "$maxspeed" route time on urban routes does not change as long as the proposed change of time per stop is maintained (60 seconds per stop).
Changing time per stop improves time routes. 60 seconds per stop is more accurate for buses, subways and trains.
Changing subway speed improves time routes in subways. Default  speed in Osmand is 60km/ for subways with 30 seconds per stop. 50 km/h and 60 seconds per stop give more accurate times.

Improving public transport

---

poi/phrases/de/phrases.xml

improved the translation of what "booth" means in german; furthermore, the meaning of "recycling:glass_bottles" goes a bit further. The translation of "traffic_signals_locate" was wrong, and in the translation of "traffic_signals_sound_no" there was missing a word for understanding it.

improved some translations

---

voice/ar/ar_tts.js

`speed_camera`: use less verbose wording
`border_control`: use less verbose wording
`railroad_crossing`: use standard expression, was: "point of crossing of trains"
`traffic_calming`: use general "traffic calming", was: "speed bump"
`toll booth`: use standard expression, was "road traffic fee"
`pedestrian_crosswalk`: use less verbose wording
`back_on_route`: use less verbose wording
Signed-off-by: Michal Fabik <michal.fabik@gmail.com>

ar_tts: Improve warnings

---

poi/poi_types.xml

OsmAnd recognises traffic_signals:vibration=yes/no and traffic_signals:arrow=yes, which is very useful, but "traffic_signals:arrow=no" was missing until now.

traffic_signals:arrow=no was missing

---

poi/poi_types.xml

recycling:small_electrical_applicances is documented in https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling and it's a bit more precise than just recycling:small_appliances. 
recycling:small_electrical_applicances gets more and more used when people want to add the information that there is the possibility to recycle these things.

added recycling:small_electrical_appliances

---

obf_creation/rendering_types.xml

Add elements in the ".obf" file for the wheelchair routing, in particular the kerb nodes its height, the elements mapped as obstacles for wheelchair and the incline tag.

New elements for a wheelchair routing

---

routing/routing.xml

Also check oneway:vehicle, oneway:motor_vehicle values, e.g. for cases when a road would be marked oneway=no, oneway:motor_vehicle=yes, which currently wouldn't work in OsmAnd (would wrongly return 'road is both ways' in car mode). Also, there are cases that have no 'oneway', but e.g. oneway:motor_vehicle=yes only.

Add hierarchical evaluation of oneway roads

---

poi/poi_types.xml

The key share_taxi=yes is listed on https://wiki.openstreetmap.org/wiki/Key:psv and is in the wiki called "uncommon", beause it's not really a vehicle type, but it is used (actual over 22000 times) at public transport platforms to show that there stop shared taxis which are usually operated on demand. Because of the frequent usage, I added it so that people can see when this tag is used on a pt platform. That's also why it put it below the pt=platform category. It's not really a vehicle class, so it does not completely fit into the access category.

Added share_taxi=yes

---

obf_creation/rendering_types.xml

Alternative solution would be:
<type tag="source:geometry" value="GPS" minzoom="13" additional="true" />
<type tag="source:geometry" value="mapillary" minzoom="13" additional="true" />
<type tag="source:geometry" value="survey" minzoom="13" additional="true" />
If country specific restriction preferred:
if_region_name="$thailand"

enable survey=ground based on source:geometry input

---

obf_creation/rendering_types.xml

Currently, the custom OBF tag survey=ground is generated when the source tag equals strictly a specific keyword.
However, source tags are allowed to use multiple values separated by semi-column (and often do): https://wiki.openstreetmap.org/wiki/Key:source
This PR enables keyword search using if_contains_tag1/if_contains_value1 combination instead of strict from_value check.

enable source multivalue keyword search to detect ground survey

---

routing/routing.xml

Dear all, I would suggest to improvements for the cobblestone settings in bicycle mode
1) In the default setting, we should add "sett" and "unhewn_cobblestone" Those were missing so far (lines 1402-1404). I would suggest that the values for sett and cobblestone should not be too far apart, because "sett" is not used too strictly in maps (often used for cobblestone that is only SLIGHTLY flattened).
2) In the avoid_sett option, sett and cobblestone should not be downgraded to less than 20%. The reason is that you can always dismount and push your bike. Or the put it the other we round: If we downgrade sett to 1% (as it was before), then to avoid just 100 meters of sett, the routing would force a detour of 10 kilometers! The 1% setting also led to long calculation times (especially if you …

Improved settings for cobblestone (bicycle)

---

routing/routing.xml

See https://github.com/osmandapp/OsmAnd/issues/13497
This solves only the first part of the issue by allowing navigation over such road segments, counter-clockwise.
Navigation instructions are still to be done (and too complicated for me)
Assumed it to be extremely unlikely for cars to encounter such situations, hence didn't implement it for those

Bidirectional navigation on junction=circular with oneway=no

---

rendering_styles/default.render.xml

Did some reordering to show service roads below links, for a better look as links rarely end up on a service road, also to make it look like the default OSM style a little more.
Before change:
After change:
OSM carto:

Put service roads below links

---

routing/routing.xml

Make the car profile observe maxwidth:physical tag set on roads and do not allow too narrow roads. See https://wiki.openstreetmap.org/wiki/Key:maxwidth:physical .
Will this work with the variable as "$maxwidth:physical", with the ":" character, which may have special effect in the declaration?

Observe maxwidth:physical limit on roads

---

obf_creation/rendering_types.xml

Remove transformations of some 'crossing' values from rendering_types.xml that no longer exist in the OSM database or are really negligible.

Remove outdated crossing values from rendering_types.xml

---

poi/poi_types.xml

Some objects do accept contactless payment, but ony for some cards. For example, some ciagrette vending machines do only accept girocard contactless payment. For this, some specific payment:xxx_contactless keys were created and they are used already/documented in the wiki. So I added them here.

Add some specific payment:xxx_contactless tags

---

rendering_styles/default.render.xml

This is an alternative approach to fix https://github.com/osmandapp/OsmAnd/issues/14391
First approach under #826
This differs from 826 in that all not-in-use railways will still be visible up to zoom level 16 (which means on my screen that you're about 400m away from it and still see it on your display, if your position is centered).
To compare, currently disused/abandoned railways will be visible on your screen up to a distance of about 1.5km (from which distance you'd probably not be able to distinguish any railway, even if it'd be on an embankment with no trees blocking the view around it)
On the other hand, it still fixes the issue that disused, preserved and construction railways (which can all look the same in real life) are rendered at completely different zoom levels. Currently a …

More-equal treatment for all non-active railways (approach 2)

---

voice/fr/fr_tts.js

And sync it with with OsmAnd/res/values-fr/strings.xml turn sharply: virez -> tournez franchement
(the sound files are incorrect by the way, they mean "turn immediately" instead of "sharply")

Fix "turn sharply" in French translation

---

routing/routing.xml

When `use_sidepath` is in use, routing should not be an option for the specific traffic. I don't know if this breaks any tests or if tests should be added to assert this behaviour.

Respect use_sidepath for bicycle, foot and horse

---

voice/pl/pl_tts.js

I think that the app should provide the complete name for tts engine because I can't really see benefit of not doing it and without it the results sound really strange with e.g. RHVoice.

Provide full name for tts engine

---

routing/routing.xml

Add coupure and height restrictor barriers to rounting.xml to explicitly mark them as passable.

Add coupure and height restrictor to rounting.xml

---

obf_creation/rendering_types.xml
rendering_styles/nautical.render.xml

Adding detail to the text display in nautical rendering for seamarks according to **[INT-1 section P](https://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_P) on [Lights](https://wiki.openstreetmap.org/wiki/Seamarks/Lights), [R Fog Signals](https://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_R) and [S Radar](https://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_S)**. This is **addressing part 1 of https://github.com/osmandapp/OsmAnd/issues/16894**, as far as possible today.
Information for the identification of navigational aids from their light character is included in the OpenStreetMap tags for **seamark:light (character, group, period), seamark:fog_signal and seamark:radar_transponder**. These are compiled to the nameTag2 seamark:light:character during the creation of …

Nautical Render INT-1, P, R, S: Lights, Fog Signals, Radar in nameTag2

---

routing/routing.xml

Formula proposed:
**percent (incline factor) * difficulty (factor) = xml_penalty_value**
1.03 * **1.5** = 1.5
1.09 * **2.5** = 2.5
1.17 * **5.5** = 6.4
1.25 * **20** = 25.0
highway=**path** gains penalty by 1.2 (**+20%**)
Actual final penalty formula is: diff (segment difference in meters) * xml_penalty_value (_formula kept as is_)
Tested (and fixed) on issue #18290
Tested on familiar terrain of Carpatian mountains (bicycle).
The issue: https://github.com/osmandapp/OsmAnd/issues/18290
Results:
base routing_cost=6800 (w/o height_obstacles)
Before proposed formula: routing_cost=115000 (16x), native lib hangs with timeout
**After proposed formula: routing_cost=22626 (3x), native lib seems OK**

Soften height_obstacles to fix issue and speed up routing (Issue #18290)

---

obf_creation/rendering_types.xml
rendering_styles/skimap.render.xml

For example, [this way](https://www.openstreetmap.org/way/158183374) mapped with the `piste:type=nordic;fatbike` tag was not displayed on the ski map, because the rendering config did not support this set of values. [OpenSnowMap](http://opensnowmap.org), however, displays it correctly, with both ski and fatbike icons.
The support is added here. Such ways are rendered as nordic ski tracks.
Also, if a piste is both `nordic` track and `hike`, we render caps on it like for `hike` pistes (see the screenshot).

Properly render ways with piste:type=* containing ;-separated values

---

obf_creation/rendering_types.xml

Enabling the `dirtbike:scale=?` tag in the OBF process will enable renderers to highlight known dirtbike routes that haven't yet been classified yet by difficulty level. This feature will help mappers prioritize enhancing these known paths and routes, improving the quality of local data for the community.
As updated in the latest OpenStreetMap wiki (Key:dirtbike:scale):
> Additionally, the dirtbike:scale=[?](https://wiki.openstreetmap.org/w/index.php?title=Tag:dirtbike:scale%3D%3F&action=edit&redlink=1) tag can be applied to routes known to accommodate dirt bikes when the precise difficulty level has not been determined.
Statistics reveal that 1,379 routes have been tagged with `dirtbike:scale=?`:
https://taginfo.openstreetmap.org/tags/dirtbike%3Ascale=%3F#overview

Enable known unclassified dirt bike routes in OBF process

---

obf_creation/rendering_types.xml

`obstacle=*` is a valuable tag that identifies ways that are challenging to navigate due to environmental obstacles.
https://wiki.openstreetmap.org/wiki/Key:obstacle
_Note that individual obstacle nodes should be typically tagged as `barrier=*`, while longer obstructed sections can be marked on ways using `obstacle:*`._
Once enabled in the OBF creation process, renderers can highlight these obstructions, similar to disused or abandoned highways, providing users with warnings. Additionally, routing systems will be able to avoid these obstructed paths.
Some of the most common obstacles covered by this PR include:

enable `obstacle=vegetation/fallen_tree` on OBF process for further rendering/routing support

---

obf_creation/rendering_types.xml

Like for dirtbikes tagging, enabling the `mtb:scale=?` tag in the OBF process will enable renderers to highlight known MTB routes that haven't yet been classified yet by difficulty level. 
This feature will help MTB mappers prioritize enhancing these known paths and routes, improving the quality of local data for the community.

enable known unclassified mtb routes

---

rendering_styles/osm-carto.render.xml

Changed admin boundaries and parking space rendering to match OSM carto.
Boundaries:
Parking spaces:

OSM carto style: admin borders & parking spaces

---

rendering_styles/routes.addon.render.xml

(I was going to submit a feature request for this, but then figured I could try figuring out the needed changes first, which worked, so now I have a PR. Let me know if you prefer to also have an accompanying feature request issue)
While planning my bicycle trips, I use osmand with (node network) routes extensively. However, cycle routes are displayed at zoom 13 and closer only, which is quite too close to plan a route from one town to the other:
Zooming out, routes disappear, even though the network node shields stay visible until zoom 11:
Zoom 11 is also a good zoom level to do rough planning of a trip, except that the routes are hidden.
This PR contains two commits. The first enables rendering of routes at zoom 11+ (from 13+), which results in:
To my taste, the route lines are a bit too …

Show cycle routes also at zoom 11/12

---

rendering_styles/default.render.xml

- Shift rendering to a dedicated section with a configurable `$roadMinZoom` (default: 14).
- Remove handling of additional tags, as `road` requires (re)surveying.
- Render as a thin line without shadow colors, using silver (`#cdcdcd`) for standard display and jet (`#2e2e2e`) for night mode.
Resolves https://github.com/osmandapp/OsmAnd/issues/20357

fix(improve-unknown-road-rendering)

---

rendering_styles/default.render.xml

I used `#3a3a3a`, but if you need something brighter, you can try `#404040` or `#4a4a4a`.
It's important that these roads don't draw too much visual attention. Unlike otherroads, they require careful consideration due to the potential for erroneous data.

make nightMode roadRoadColor slightly darker

---

obf_creation/rendering_types.xml

I hope it is fine to propose this addition this way.
Adding footway=sidewalk to the list of additional tags allows to make the maps in cities more readable while still showing footways e.g. in parks in a lower zoom level.

add footway=sidewalk as additional tag

---

routing/routing.xml

https://wiki.openstreetmap.org/wiki/Tag:service%3Dalley
In some regions, chiefly in Europe, narrow streets in historic cities that provide access to the main entrances of buildings may also be mapped as alleys, distinguishing them from wider modern streets mapped, for example, as [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[residential](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dresidential).
To Do

[5.1] Improve pedestrian routing (service=alley, etc)
