routing/routing.xml
Proposal for:
https://code.google.com/p/osmand/issues/detail?id=2566
=> Improve access rules

voice/it/ttsconfig.p
Changed words order in "Route calculated.." phrases
=> Little words change

voice/it/ispeech_it.csv
Riagganciato al posto di restaurato (segnale GPS)
=> minor change

voice/it/ttsconfig.p
=> Little change in "prepare to"

voice/it/ttsconfig.p
Fixed some misprint from german in "follow the"
=> Fixed some misprint from german

routing/routing.xml
Sorry, there was a typo in my previous patch.
=> Fix typo in routing.xml

obf_creation/rendering_types.xml
I am not sure what to do with the duplicate to_tag2 at line 1111 (wikipedia at aerodrome). Should it be to_tag3?
=> Fix duplicate attributes in rendering_types.xml

routing/routing.xml
Remove unused oneway values, similarly to car profile.
=> Remove unused oneway tags in routing.xml bike profile

voice/es/ttsconfig.p
I have Changed line 120: string('to.ogg', 'hacia').
=> Update ttsconfig.p (Spanish)

voice/sk/ttsconfig.p
I have now tested this via the OsmAnd Development plugin voice command tests and with a TTS module having Slovak. These are some tweaks needed to get proper sentences with "prepare" and proper plural forms for kilometers, miles, hours and minutes.
=> Update Slovak TTS config

routing/routing.xml
Create new option to avoid shuttle trains (similar to ferries)
Resolves https://github.com/osmandapp/Osmand/issues/1308
=> Allow shuttle trains

obf_creation/rendering_types.xml, poi/phrases/de/phrases.xml, poi/phrases/en/phrases.xml, poi/phrases/es/phrases.xml, poi/phrases/fr/phrases.xml, poi/phrases/it/phrases.xml, poi/phrases/pt/phrases.xml, poi/poi_types.xml
Added Paediatrics to make it easier to find these when travelling
=> Added Paediatrics 

voice/es/ttsconfig.p
Changed 2 items not translated into spanish
=> Update spanish ttsconfig.p

voice/gen_voice.sh
Cleanup some trailing whitespace and add some error checking for missing files. Also update the documentation to help with the problems I encountered while running the script.
=> Improve gen_voice.sh debugging

voice/hu/ttsconfig.p
Support announcement of railroad crossings and pedestrian crosswalks
=> Update hungarian ttsconfig.p

voice/es/ttsconfig.p
Announcement when user returns back to route
Support announcement of railroad crossings and pedestrian crosswalks
and remove some "prepare" for similarity with the english file
=> update ttsconfig.p (es)

routing/routing.xml
Ways with bicycle=dismount are allowed for bikes, but use a walking speed for them and lower their priority.
=> Support bicycle=dismount in rounting.xml

routing/routing.xml
I've found many points marked with crossing=no where route should normally go along highway via this point.
http://www.openstreetmap.org/node/3601443925
http://www.openstreetmap.org/node/2042635591
=> Dont't avoid crossing=no

routing/routing.xml
highway=byway is converted to track in rendering_types.xml
highway=services is not stands for the routing line
=> Remove byway and services from routing.xml

obf_creation/rendering_types.xml, rendering_styles/default.render.xml, routing/routing.xml
http://wiki.openstreetmap.org/wiki/Key:bicycle road
Bicycle roads are much better for cyclists than common roads, so it worth to prefer them in routing.xml and render additional dashed line similar to cycleway=lane, but using cycleway style.
https://www.dropbox.com/s/bh9tk47touiz6e9/bicycle_road.png?dl=0
=> Add bicycle_road=yes

voice/sk/ttsconfig.p
Update to all the latest features, tested and fixed grammar. Also not(tts) works for all the features (will upload separately).
=> Update Slovak ttsconfig.p

voice/sk/config.p
This file was generated from the sk/ttsconfig.p via gen_voice.sh.
I also gave the generated ogg files, that were created using 'gen_voice.sh sk Slovak google sk' and TEMP_FACTOR=1.3 . Should I upload it here somehow? If yes, how? Or will you generate the package yourself?
This package replaces sk-Ruzena package, that was outdated and is no longer offered for download.
=> Update config.p for Slovak

voice/cs/ttsconfig.p
Would it be possible to update prerecorded voices with the changes, please?
=> Translate missed strings and correct declension

voice/fr/ttsconfig.p
Improve French translation by using meaningful words and actually used sentences (ie. not Google-translated ones!).
=> fr-tts: Fix and improve French words

voice/ja/ttsconfig.p
Changed some scripts to that commonly used by automotive navigation system of Japanese.
(This pull request includes the change of #403 to avoid conflict .)
=> fix unnatural Japanese scripts

obf_creation/rendering_types.xml
this should fix https://github.com/osmandapp/Osmand/issues/3315
=> fix rendering highway=corridor

routing/routing.xml
Add more weights into routing.xml, based on European limits.
See https://groups.google.com/forum/#!topic/osmand/6_Xp0ZDXWVw .
=> Add more weights into routing.xml

voice/pl/config.p
Previous meaning was "bump", new one is "traffic calming".
=> Make warning for traffic calming more general (Polish)

voice/es/ttsconfig.p
I would like there were agreement on traslation of "onto" in spanish.  Can any spanish people check this pull request?
This is not the best literal traslation but I think this is the best traslation in order to put it on OSMAND.
=> Update ttsconfig.p (spanish - add "onto")

voice/cs/ttsconfig.p
Replaces weird phrases with more natural way to say it. Uses workaround for “towards” which sounded strange due to missing declination of the destination name.
=> Updated Czech TTS

voice/uk/ttsconfig.p
As far as I see, this config was poorly translated directly from russian. I've made some corrections to avoid any kind of laughing.
=> Corrections for uk translation

routing/routing.xml
Hello to everyone who is involved with Osmand development,
thank you for the new bicycle routing! The inclusion of elevation data is incredibly good. I am really impressed by how you implemented this! The graphic display was the biggest surprise - and works perfectly. 
I have some suggestions for further improvements in bicycle routing. This is the first part (second will follow in the next days). My two suggestions are below in the commentary (in the routing.xml I have just deleted an " ß " . This character leads to some android browsers being unable to display the file). 
Now, my first two suggestions:
1.)  If a footway is marked as “sidewalk”, this is not recognisable in the Osmand maps at the moment. There is already a corresponding command in the routing.xml, but at the moment, it …
=> Proposals for bicycle routing - Part 1

routing/routing.xml
Dear all,
based on the discussion so far, I have created a new pull request. I have left out all the suggestions that do not seem necessary any more. 
But still there are same changes that would be helpful. Could you include these into the next Osmand update, please?
Would it be possible to also make Osmand able to "see" footway=sidewalk and highway=elevator while routing? The first one would even be an urgent update, I think. 
Also, the triple counting of traffic lights would be important to solve in my opinion. But this is obviously more complicated. 
Thank you very much
Malte
=> Revised pull request

voice/uk/ttsconfig.p
Original voice: Після 150 метрів крапка о поверіть праворуч
Proposed voice: Через 150 метрів крапка о поверіть праворуч
=> Improving of translation. uk-ua

routing/routing.xml
I did a revision of the routing.xml
Please check it and include it in the July update, if still possible.
The proposed changes are based on much testing and research (for example much research on the quality of bicycle routes)
=> Some additional improvements

voice/fi/ttsconfig.p
Check commit message for full details.
I transferred the file to a device and used the development tools in OsmAnd to listen through all the examples in the voice prompts section.
=> Improvements to Finnish voice guidance

rendering_styles/default.render.xml
**Show nameTag2="ele" with tag="mountain_pass"**
*nameTag2="ele"* never performed with *tag="mountain_pass"* due to
<apply_if hideHouseNumbers="false" nameTag2="addr:housenumber"/>
Issue should be fixed now.
=> Show nameTag2="ele" with tag="mountain_pass"

rendering_styles/default.render.xml
*Add ele to mountain buildings*
Add *nameTag2="ele"* to chalet, alpine_hut, cabin, lean_to, wilderness_hut and shelter, by keeping all other "Accommodations" unaltered (with *nameTag2="addr:housenumber"*)
=> Add ele to mountain buildings

obf_creation/rendering_types.xml
With this update all routing profiles from OsmAnd should be supported.
=> Update country specific living_street access

rendering_styles/default.render.xml
Add a label for *natural=fell*.
Ref. https://wiki.openstreetmap.org/wiki/Tag%3Anatural%3Dfell
=> Add label for natural=fell

voice/nb/ttsconfig.p
Created a norwegian (nb) ttsconfig.p file.
Don't know how to make the sound files, but if someone can create norwegian voice guidance in OsmAnd on basis of this file it would be nice.
=> Norwegian (nb) ttsconfig.p

routing/routing.xml
A fresh pull of the master repo, amended with tons of documentation.
=> Added documentation to routing.xml

voice/sc/config.p, voice/sc/ispeech_sc.csv, voice/sc/ttsconfig.p
Updates for Sardinian (sc) voice files.
=> Sardinian voice files updated

voice/README.md
update Readme according to switch from prolog to js
=> update Readme according to switch from prolog to js

routing/routing.xml
https://github.com/osmandapp/Osmand/issues/4455#issuecomment-432255700
=> use elevation data for routing by default

voice/nb/nb_tts.js
Referring to former pull request (https://github.com/osmandapp/OsmAnd-resources/pull/492)
=> Norwegian (nb) tts.js

voice/sv/sv_tts.js
corrected långsammare trafik (slower traffic) to farthinder (traffic calming)
=> corrected traffic calming

obf_creation/rendering_types.xml
Add urban and rural speeds limits from France country
=> Add Fr speeds limits in rendering_types.xml

obf_creation/rendering_types.xml, rendering_styles/skimap.render.xml, routing/routing.xml
See discussion thread in [#5021](https://github.com/osmandapp/Osmand/issues/5021).
=> Ski profile for planning routes (#5021)

voice/sv/sv_tts.js
Removed duplicate "och ta"(and take) in Swedish roundabout announcement.
=> Removed duplicate "och ta" in Swedish roundabout anouncment.

routing/routing.xml
Remove unused motorcycle reference in car profile in routing.xml.
=> Remove unused motorcycle reference in routing.xml

routing/routing.xml
Clean up some typos and long lines in documentation in the head block of routing.xml.
=> Clean up docs in routing.xml

routing/routing.xml
Reformat the <if param="avoid_ice_roads_fords"> block to the new preferred notation (<select>s inside <if>) so it is also clearer to read.
=> Reorder <if param="avoid_ice_roads_fords"> in routing.xml

voice/sk/sk_tts.js
Clean up some leading and trailing spaces/tabs and simplify logic for time() strings.
=> clean up and simplify sk_tts.js

voice/hr/hr_tts.js
(X) Special grammar: plural forms for numbers 2-4
(X) Special grammar: word order with clitics ("onda se držite lijevo")
(X) Special grammar: grammatical gender and case for numbers ending with 1 and 2 ("udaljenost je jedna milja", "nakon jedne milje", "za jednu milju" etc.)
Tested with Vocalizer TTS engine for Croatian.
Signed-off-by: Michal Fabik <mfabik@redhat.com>
=> Fix grammar for numbers, word order; translation fixes

voice/sr/sr_tts.js
Initial commit, adapted from Croatian
Tested with Vocalizer voice for Croatian
Signed-off-by: Michal Fabik <michal.fabik@gmail.com>
=> Add Serbian directions

voice/bs/bs_tts.js
Initial commit, adapted from Croatian
Tested with Vocalizer voice for Croatian
Signed-off-by: Michal Fabik <michal.fabik@gmail.com>
=> Add Bosnian directions

voice/cs/cs_tts.js
I can hear voice "undefined" now
=> Fix go_ahead configuration and voice for distance from 3 to 4 kilometers for  czech voice

voice/es/es_tts.js
related to what I said in https://github.com/osmandapp/OsmAnd-resources/pull/572. I think turn slightly is better tahan turn because of Look at http://www.gpspassion.com/forumsen/topic.asp?TOPIC_ID=36357 (message 3).
=> Little improvements in Spanish TTS

voice/es/es_tts.js
Fix double  [+ " " +"]
https://github.com/osmandapp/OsmAnd-resources/pull/576#issuecomment-516141105
Thanks to @aceman444
=> Fix mistake last update

poi/phrases/en/phrases.xml, poi/poi_types.xml
update poi_types.xml: added filter for payment:euroshell=yes/no for amenity=fuel
update phrases.xml: added Phrases for POI fIlter for payment:euroshell
=> added filter for amenity=fuel (payment:euroshell=yes/no)

voice/it/it_tts.js
Now lenght will be promt only one time in the sentence of the route calculation.
=> Delete a "length" that was one more

voice/uk/uk_tts.js
Still draft. Will add some more fixes.
=> Improved Ukrainian TTS

voice/zh-tw/zh-tw_tts.js
I added zh-tw TTS file, please review and merge it :smiley:
=> Add zh-tw voice.

voice/es/es_tts.js
As I said in https://github.com/osmandapp/OsmAnd-resources/pull/609
=> Spanish Improvements

poi/phrases/uk/phrases.xml
Added:
<string name="poi_pump_status_out_of_order">Стан насоса: не функціонує</string>
<string name="poi_pump_status_missing_beam">Стан насоса: відсутній важіль</string>
=> Added poi_pump_status_out_of_order and poi_pump_status_missing_beam

poi/phrases/ru/phrases.xml
Added:
<string name="poi_pump_status_out_of_order">Состояние насоса: не функционирует</string>
<string name="poi_pump_status_missing_beam">Состояние насоса: отсутствует рычаг</string>
=> Added "poi_pump_status_out_of_order" and  "poi_pump_status_missing_beam"

poi/poi_types.xml
Added:
<poi_additional name="pump_status_out_of_order" tag="pump:status" value="out_of_order"/>
=> Added "pump_status_out_of_order"

voice/hu-formal/hu-formal_tts.js
Previous attention message was unnecessarily long
=> Update a translation

voice/zh-tw/zh-tw_tts.js
I updated zh-tw tts, please review and merge it :smiley:
=> Update zh-tw tts.

poi/poi_types.xml
add recognizing traffic_signals:vibration=yes/no for crossing=traffic_signals-nodes - see part of in https://github.com/osmandapp/Osmand/issues/6883
=> add support of traffic_signals:vibration

voice/zh-tw/zh-tw_tts.js
I updated traffic calming translation to speed bump to align with en, please review and merge it :smiley:
=> Update zh-tw to align with en.

routing/routing.xml
bus speed= "$maxspeed" requires maxDefaultSpeed to be 95.
=> maxDefaultSpeed for public transport

obf_creation/rendering_types.xml, routing/routing.xml
https://github.com/osmandapp/OsmAnd/issues/9645
=> Issue 9645 Support oneway:foot 

voice/tr/tr_tts.js
Corrected some grammer errors. Added missing translations.
=> Turkish translation improvements

voice/tr/tr_tts.js
Corrected grammer errors and  order at sentences
=> Grammer and pronounciation corrections

voice/bg/bg_tts.js
I use [eSpeak NG](https://play.google.com/store/apps/details?id=com.redzoc.ramees.tts.espeak) to test it but Bulgarian synth is not so good :(
I hope this helps to some to make it better
=> translate for Bulgarian TTS

protos/OBF.proto
Added new fields in OBF.proto: preciseDx, preciseDy for POI
=> Added new fields in OBF.proto: preciseDx, preciseDy for POI

poi/poi_types.xml
Based on https://wiki.openstreetmap.org/wiki/Climbing#Grading
=> Added POI types for minimum climbing grade

voice/id/id_tts.js
I'm adding TTS for Indonesian Language
=> Adding TTS for Indonesian

voice/zh-tw/zh-tw_tts.js
I updated zh-tw tts voice to align with en, please review and merge it :smiley:
=> Update zh-tw tts to align with en.

routing/routing.xml
https://wiki.openstreetmap.org/wiki/Key:conveying
=> Add conveying tag in pedestrian routing profile

routing/routing.xml
Add Routing for Horsebackriding
OSMand would be the ideal navigation system for horse riding as all the necessary data is contained in OSM.
There are currently no comparable navigation systems on the market.
=> New: Horsebackriding

poi/phrases/de/phrases.xml
Added the German translations for the newly added keys "callable", two new payment methods, "manufacturer" and "model_type (key:model)".
=> Added German translations for some newly added keys

poi/phrases/en/phrases.xml
Added translations for the newly added keys "callable", two new payment methods, "manufacturer" and "model_type (key:model)".
=> Added translations for some newly added keys

routing/routing.xml
Minimal needed changes for fix https://github.com/osmandapp/OsmAnd/issues/12911
=> Issue 12911

routing/routing.xml
=> add platform to penalty_transition with 0

obf_creation/rendering_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/15483
=> Undo remove tag natural=coastline for islands

obf_creation/rendering_types.xml, rendering_styles/default.render.xml, rendering_styles/topo.render.xml, routing/routing.xml
Add support tag cycleway:both=share_busway rooting and rendering.
Add others cycleway and cycleway:both missing.
Issue https://github.com/osmandapp/OsmAnd/issues/10053
=> Axelos cyclewayboth=share busway

voice/pl/pl_tts.js
Examples:
`in 2 minutes` should be `za dwie minuty` instead of `za dwa minut` (two should be in female form, minuts should have proper grammar form)
`in 3 minutes` should be `za trzy minuty` instead of `za trzy minut` (minutes should have proper grammar form)
`in 22 minutes` should be `za dwadzieścia dwie minuty` instead of `za dwadzieścia dwa minut` (two should be in female form, minuts should have proper grammar form)
It's partially related to https://github.com/osmandapp/OsmAnd/issues/4453
=> TTS pl - support for special grammar

voice/pl/pl_tts.js
fixes: https://github.com/osmandapp/OsmAnd/issues/7570#issuecomment-907590326
tested on emulator using Google TTS
3.4
There is:
Za około **trzech** **kilometrów** skręć w prawo w SR **osiemdziesięciu** w kierunku Rome.
Expected
Za około **trzy** **kilometry** skręć w prawo w SR **osiemdziesiąt** w kierunku Rome.
3.5 (Route 23)
There is:
Za trzysta pięćdziesiąt metrów skręć w lekko w prawo w Route **dwudziestu** trzech Main Street, następnie trzymaj się lewej strony.
Expected:
Za trzysta pięćdziesiąt metrów skręć w lekko w prawo w Route **dwadzieścia** trzy Main Street, następnie trzymaj się lewej strony.
3.11 (to exit 260B)
There is:
... w zjazd **dwustu sześćdziesięciu** B
Expected:
... w zjazd **dwieście sześćdziesiąt** B
3.12 (to exit 15B)
There is:
... w zjazd **piętnastu** B …
=> TTS-PL fixes street/exit names in 3.11 3.12 4.3 5.2 5.3

voice/nb/nb_tts.js
Some more improvements to nb_tts.js
=> Update for norwegian (nb) tts.js

rendering_styles/osm-carto.render.xml
Changes to the OSM rendering style to match OSM Carto better.
Changed `natural=wetland` - `wetland=tidalflat` and `natural=sand`
=> OSM rendering style changes

.editorconfig, obf_creation/rendering_types.xml, routing/routing.xml
I've been working on a custom profile for mopeds for some time, but since some extra data is needed in the obf files (inferring speed from [`zone:traffic`](https://wiki.openstreetmap.org/wiki/Key:zone:traffic)) and I was making a PR for that, I figured I could just as well share the rest of my efforts too.
Some questions:
1. I see that `bicycle=use_sidepath` is [transformed](https://github.com/osmandapp/OsmAnd-resources/blob/2915920078e17fdd215557ffdfdde5bcd3f273fa/obf_creation/rendering_types.xml#L205) to `bicycle:no` (although that would make [this](https://github.com/osmandapp/OsmAnd-resources/blob/2915920078e17fdd215557ffdfdde5bcd3f273fa/routing/routing.xml#L1231) seem superfluous). Would this be a good thing to do for `moped=use_sidepath` too? It might help keep the data size down, a …
=> A basic profile for mopeds

protos/OBF.proto
To issue https://github.com/osmandapp/OsmAnd-Issues/issues/1885
=> Add OsmAndOwner to obf

test-resources/test_turn_lanes.json
To issue https://github.com/osmandapp/OsmAnd/issues/15559
=> Avoid keep left/right on through moving

voice/ru/ru_tts.js
Added small distance rounding.
=> Distance voicing errors have been fixed

poi/poi_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/17335
=> Decrease order for atm=yes and building=yes

voice/beep-complex-loud/beep-complex-loud_tts.js, voice/beep-complex/beep-complex_tts.js
@sonora 
Sorry, not sure that was the right way to go about switching it round to the other way, but this seems to have worked :)
But yeah, it makes sense to have it consistent with all the other checks.
Thanks for your assistance.
ref #1001
=> Change comparison operators in beep voice packs for consistency 

obf_creation/rendering_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/17401
=> Add option propagateToNodes

list-resources.py
This reverts commit 783960d3ad99e52f8fa2484447069e2a49f6ca70.
=> Revert "Temporarily use png for tools"

voice/ta-in/pack_rec_voice_std.sh, voice/ta-in/ta-in_tts.js
Added support for Tamil (India) - TTS.
=> Support for Tamil (India) TTS

obf_creation/rendering_types.xml
Relation id tags before map generation 01.04.2024
To issues https://github.com/osmandapp/OsmAnd-Issues/issues/2375
https://github.com/osmandapp/OsmAnd/issues/14938
=> Support relation_id tag in routes

voice/lt/lt_tts.js
Lithuanian language has several plural forms, different genders, and grammatical cases depending on context.
Implementation is based primarily on Serbian, partly on English, partly on Latvian examples, and expanded/corrected for Lithuanian needs. 
Some basic JS testing is done. More testing is welcome.
=> Initial Lithuanian TTS

obf_creation/rendering_types.xml, routing/routing.xml
To issue https://github.com/osmandapp/OsmAnd/issues/6954
=> Add support red_turn:straight:bicycle

poi/poi_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/16397
Together with PR: https://github.com/osmandapp/OsmAnd/pull/19898 and https://github.com/osmandapp/OsmAnd-tools/pull/866
=> Add top_index max_per_map min_count for poi_additional

rendering_styles/default.render.xml
See https://github.com/osmandapp/OsmAnd/issues/20208
Examples:
| Default street style | Pale street style |
| ------------- | ------------- |
| Base map |
| <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/f411b301-5ad6-4b25-9bdb-870424c532da" height=300>  | <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/34362162-f3e9-42df-af43-9a70e3178e26" height=300>  |
| Public transport (tram + bus) |
| <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/786af3b7-f9d7-4ba9-b0aa-bc3e1fe664d5" height=300>  | <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/9386e84c-d8db-42e9-8567-0a8545d33b15" height=300>  |
| Bicycle routes |
| <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/7c5d1b56-2d98-4fc2-82f8- …
=> Introduce a new road-style "pale"

poi/poi_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/16397
=> Add lang support for top_index

voice/lt/lt_tts.js
Otherwise Lithuanian TTS may not work in OsmAnd
=> Fix lt_tts.js by replacing "let" into "var"

routing/routing.xml
Set obstacle to 0 for highway=give_way in _short_way_ mode.
To issue https://github.com/osmandapp/OsmAnd/issues/20078
=> Fix routing

voice/et/et_tts.js
- Added declension support for integers
- Fixed language & pronunciation errors
- Fixed bugs e.g dictionary keys being passed to TTS
=> Fix and add features to Estonian TTS

poi/poi_types.xml
Add two more payment methodes: the parking-apps "Parkster" and "Parco" do have their own values.
=> Update poi_types.xml (add parco and parkster payment methods)

obf_creation/rendering_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/8159
=> Add osmand_poi_lat_lon

obf_creation/rendering_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/21111
=> Avoid name:signed in tags

voice/pl/pl_tts.js
solves [https://github.com/osmandapp/OsmAnd/issues/6088](https://github.com/osmandapp/OsmAnd/issues/6088)
=> #6088 force TTS to use correct PL number forms in street name

poi/poi_types.xml
To issue https://github.com/osmandapp/OsmAnd/issues/22197
Софійський монастир
=> protected_area order

obf_creation/rendering_types.xml, rendering_styles/default.render.xml
https://github.com/osmandapp/OsmAnd-Issues/issues/2772
=> Optimize read z11

countries-info/regions.xml
https://github.com/osmandapp/OsmAnd/issues/21801 ("Other maps" cleanup)
=> Add wiki="yes" to Australia in regions.xml

rendering_styles/map-legend/default.legend.xml
https://github.com/osmandapp/OsmAnd/issues/9995
=> Reformat default.legend.xml for new legend translation
